jobs:
  - job: devops project
    displayName: "Linting"
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "14.x"
        displayName: "Install Node.js"

      - script: |
          npm install
          npx eslint index.js
        displayName: "Lint JavaScript/TypeScript files"
